version: '3.8'

services:
  api:
    build: .
    container_name: forecasting-api
    restart: unless-stopped
    ports:
      - "5289:5289"
    depends_on:
      - db
    environment:
      - ml-engine-url=http://ml-engine:8000
      - ASPNETCORE_URLS=http://+:5289
      - ConnectionStrings__Default=Host=db;Port=5432;Database=forecastingprod;Username=admin;Password=${DB_PASSWORD}

  db:
    image: postgres:15
    container_name: postgres-prod
    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: forecastingprod

    volumes:
      - /opt/postgres-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  ml-engine:
    build: ../../ML-Engine-Forecasting
    container_name: ml-engine
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - API_URL=http://api:5289
    ports:
      - "8000:8000"
